site:
  title: Kaskada Docs
  start_page: kaskada::index.adoc
  robots: allow
  # url: TBD
content:
  sources:
    - url: https://github.com/kaskada-ai/kaskada.git
      branches: main
      start_path: docs-src
      worktrees: true

asciidoc:
  sourcemap: true
  extensions:
    - ./lib/generate_stream_viz.js
    - asciidoctor-kroki
  attributes:
    kroki-fetch-diagram: true
    page-pagination: ""
    sectanchors: ""
    sectlinks: ""
    idprefix: ""
    idseparator: "-"
    table-stripes: even

ui:
  bundle:
    url:  https://github.com/kaskada-ai/docs-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
