site:
  title: LOCAL Kaskada Docs
  start_page: kaskada::index.adoc
  robots: allow
  # url: <TBD>
content:
  sources:
    - url: .
      branches: docs-build
      start_path: docs-src
      worktrees: true

asciidoc:
  sourcemap: true
  attributes:
    page-pagination: ""
    sectanchors: ""
    sectlinks: ""
    idprefix: ""
    idseparator: "-"
    table-stripes: even

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui