name: PR
on:
  pull_request:
    branches: [main]
  workflow_call: 
  # Allow manual triggering of this workflow
  workflow_dispatch:
    inputs:
      # Allow the user to specify whether to publish the site or not
      branch:
        description: 'Branch on kaskada-ai/kaskada use for this build.'
        required: true
        default: 'main'


# In cases of concurrent workflows running (consecutive pushes to PR)
# leave the latest workflow and cancel the other (older) workflows
# See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr_build:
    name: PR Build (no publish)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout kaskada-ai/kaskada branch for workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v3
        with:
          repository: kaskada-ai/kaskada
          ref: ${{ github.event.inputs.branch }}
          path: kaskada_branch

      - name: Checkout kaskada-ai/kaskada branch for PR
        if: github.event_name != 'workflow_dispatch'
        uses: actions/checkout@v3
        with:
          repository: kaskada-ai/kaskada
          ref: main
          path: kaskada_branch

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Antora
        run: npm i antora

      - name: Generate Site
        env:
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
        run: npx antora --log-failure-level=warn antora-playbook-PR.yml --stacktrace

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs-site
          path: |
            build/site
